using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AMS.Core.DTOs;
using AMS.Core.Entities;
using AMS.Core.Interfaces;
using AMS.Infrastructure.Data;

namespace AMS.WebAPI.Controllers;

/// <summary>
/// Clients Controller - Manages CRUD operations for clients
/// 
/// THE REQUEST/RESPONSE FLOW:
/// 
/// 1. Client (browser/app) makes HTTP request
/// 2. Request passes through middleware (auth, logging, etc.)
/// 3. ASP.NET Core routes request to this controller
/// 4. Controller action executes (calls repository)
/// 5. Repository queries/updates database via EF Core
/// 6. EF Core generates and executes SQL
/// 7. Data flows back: SQL → EF → Repository → Controller → HTTP Response
/// </summary>
[ApiController]
[Route("api/[controller]")]  // Route = /api/clients
[Authorize]  // All endpoints require authentication
public class ClientsController : ControllerBase
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly AMSDbContext _context;  // Direct context for complex queries
    private readonly ILogger<ClientsController> _logger;
    
    public ClientsController(
        IUnitOfWork unitOfWork,
        AMSDbContext context,
        ILogger<ClientsController> logger)
    {
        _unitOfWork = unitOfWork;
        _context = context;
        _logger = logger;
    }
    
    /// <summary>
    /// GET /api/clients
    /// Returns all clients
    /// 
    /// SQL Generated by EF Core:
    /// SELECT * FROM Clients WHERE IsActive = 1
    /// </summary>
    [HttpGet]
    public async Task<ActionResult<IEnumerable<ClientDto>>> GetClients()
    {
        _logger.LogInformation("Getting all clients");
        
        var clients = await _context.Clients
            .Where(c => c.IsActive)
            .Include(c => c.Policies)  // Include related policies (JOIN)
            .OrderBy(c => c.LastName)
            .Select(c => new ClientDto
            {
                Id = c.Id,
                FirstName = c.FirstName,
                LastName = c.LastName,
                Email = c.Email,
                Phone = c.Phone,
                Address = c.Address,
                City = c.City,
                State = c.State,
                ZipCode = c.ZipCode,
                DateOfBirth = c.DateOfBirth,
                CreatedAt = c.CreatedAt,
                PolicyCount = c.Policies.Count(p => p.IsActive)
            })
            .ToListAsync();
        
        return Ok(clients);
    }
    
    /// <summary>
    /// GET /api/clients/{id}
    /// Returns a specific client by ID
    /// 
    /// SQL Generated:
    /// SELECT * FROM Clients WHERE Id = @id AND IsActive = 1
    /// </summary>
    [HttpGet("{id}")]
    public async Task<ActionResult<ClientDto>> GetClient(Guid id)
    {
        _logger.LogInformation("Getting client with ID: {Id}", id);
        
        var client = await _context.Clients
            .Where(c => c.Id == id && c.IsActive)
            .Include(c => c.Policies)
            .Select(c => new ClientDto
            {
                Id = c.Id,
                FirstName = c.FirstName,
                LastName = c.LastName,
                Email = c.Email,
                Phone = c.Phone,
                Address = c.Address,
                City = c.City,
                State = c.State,
                ZipCode = c.ZipCode,
                DateOfBirth = c.DateOfBirth,
                CreatedAt = c.CreatedAt,
                PolicyCount = c.Policies.Count(p => p.IsActive)
            })
            .FirstOrDefaultAsync();
        
        if (client == null)
        {
            return NotFound(new { message = "Client not found" });
        }
        
        return Ok(client);
    }
    
    /// <summary>
    /// POST /api/clients
    /// Creates a new client
    /// 
    /// Flow:
    /// 1. Deserialize JSON body into CreateClientDto
    /// 2. Validate data (automatic with [ApiController])
    /// 3. Create new Client entity
    /// 4. Add to DbContext (marks for insertion)
    /// 5. SaveChanges (executes INSERT SQL)
    /// 6. Return created client with 201 status
    /// </summary>
    [HttpPost]
    public async Task<ActionResult<ClientDto>> CreateClient([FromBody] CreateClientDto dto)
    {
        _logger.LogInformation("Creating new client: {Email}", dto.Email);
        
        // Check if email already exists
        var emailExists = await _unitOfWork.Clients.ExistsAsync(c => c.Email == dto.Email);
        if (emailExists)
        {
            return BadRequest(new { message = "A client with this email already exists" });
        }
        
        // Create entity from DTO
        var client = new Client
        {
            FirstName = dto.FirstName,
            LastName = dto.LastName,
            Email = dto.Email,
            Phone = dto.Phone,
            Address = dto.Address,
            City = dto.City,
            State = dto.State,
            ZipCode = dto.ZipCode,
            DateOfBirth = dto.DateOfBirth
        };
        
        // Add to repository (marks for insertion)
        await _unitOfWork.Clients.AddAsync(client);
        
        // Save changes (executes INSERT SQL)
        await _unitOfWork.SaveChangesAsync();
        
        _logger.LogInformation("Created client with ID: {Id}", client.Id);
        
        // Return 201 Created with location header
        var result = new ClientDto
        {
            Id = client.Id,
            FirstName = client.FirstName,
            LastName = client.LastName,
            Email = client.Email,
            Phone = client.Phone,
            Address = client.Address,
            City = client.City,
            State = client.State,
            ZipCode = client.ZipCode,
            DateOfBirth = client.DateOfBirth,
            CreatedAt = client.CreatedAt,
            PolicyCount = 0
        };
        
        return CreatedAtAction(nameof(GetClient), new { id = client.Id }, result);
    }
    
    /// <summary>
    /// PUT /api/clients/{id}
    /// Updates an existing client
    /// 
    /// Flow:
    /// 1. Find existing client by ID
    /// 2. Update only provided fields
    /// 3. Save changes (executes UPDATE SQL)
    /// </summary>
    [HttpPut("{id}")]
    public async Task<ActionResult<ClientDto>> UpdateClient(Guid id, [FromBody] UpdateClientDto dto)
    {
        _logger.LogInformation("Updating client with ID: {Id}", id);
        
        var client = await _unitOfWork.Clients.GetByIdAsync(id);
        if (client == null)
        {
            return NotFound(new { message = "Client not found" });
        }
        
        // Update only provided fields
        if (!string.IsNullOrEmpty(dto.FirstName)) client.FirstName = dto.FirstName;
        if (!string.IsNullOrEmpty(dto.LastName)) client.LastName = dto.LastName;
        if (!string.IsNullOrEmpty(dto.Email)) client.Email = dto.Email;
        if (!string.IsNullOrEmpty(dto.Phone)) client.Phone = dto.Phone;
        if (!string.IsNullOrEmpty(dto.Address)) client.Address = dto.Address;
        if (!string.IsNullOrEmpty(dto.City)) client.City = dto.City;
        if (!string.IsNullOrEmpty(dto.State)) client.State = dto.State;
        if (!string.IsNullOrEmpty(dto.ZipCode)) client.ZipCode = dto.ZipCode;
        
        _unitOfWork.Clients.Update(client);
        await _unitOfWork.SaveChangesAsync();
        
        _logger.LogInformation("Updated client with ID: {Id}", id);
        
        return Ok(new ClientDto
        {
            Id = client.Id,
            FirstName = client.FirstName,
            LastName = client.LastName,
            Email = client.Email,
            Phone = client.Phone,
            Address = client.Address,
            City = client.City,
            State = client.State,
            ZipCode = client.ZipCode,
            DateOfBirth = client.DateOfBirth,
            CreatedAt = client.CreatedAt
        });
    }
    
    /// <summary>
    /// DELETE /api/clients/{id}
    /// Soft deletes a client (sets IsActive = false)
    /// </summary>
    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteClient(Guid id)
    {
        _logger.LogInformation("Deleting client with ID: {Id}", id);
        
        var client = await _unitOfWork.Clients.GetByIdAsync(id);
        if (client == null)
        {
            return NotFound(new { message = "Client not found" });
        }
        
        _unitOfWork.Clients.Delete(client);  // Soft delete
        await _unitOfWork.SaveChangesAsync();
        
        _logger.LogInformation("Deleted client with ID: {Id}", id);
        
        return NoContent();  // 204 No Content
    }
}
